package com.trustagro.user.entity;

public enum Role {
    ADMIN,
    GENERAL_MANAGER,
    OPERATIONS_MANAGER,
    FARM_MANAGER,
    VETERINARY_OFFICER,
    STORE_KEEPER,
    PHARMACY_SALES,
    FINANCE_OFFICER,
    EXTENSION_WORKER
}
